# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables: # terraform variables
 ServiceConnectionName: 'anynameofsp'
 bk-rg-name: 'rg-name'
 bk-str-account-name: 'strname'
 bk-container-name: 'containername'
 bk-key: 'terraform.tfstate' # key is actually name of the file, determined here
 
pool:
  vmImage: ubuntu-latest
  
stages:

  - stage: validate_terraform
    displayName: 'Validate Terraform'

    jobs:
    - template: Terraform/plan.yml
      parameters:
        env: dev

  - stage: deploy_terraform
    displayName: 'Deploy Terraform'
    dependsOn:
    - validate_terraform # makes sure validate_terraform stage runs first
    condition: succeeded('validate_terraform') ## stage runs only if validate_terraform is successful

    jobs:
    - template: Terraform/deploy.yml
      parameters:
        env: dev
    

