# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: prep_terraform
    displayName: "Setup terraform"
    
    steps:
      - task: TerraformInstaller@2
        inputs:
          terraformVersion: 'latest'
      
      - task: TerraformCLI@2
        inputs:
          command: 'init'
          backendType: 'azurerm'
          allowTelemetryCollection: true
