location              = "uksouth"
vm_size               = "Standard_DS1_v2"
teamname              = "teamb"
environment           = "dev"
private_address_space = "10.0.0.0/16"
vm_username           = "teambadmin"
lb_sku_tier           = "Regional"
sql_username          = "teambsqladmin"
