jobs:
  - job: deply_terraform
    displayName: "Deploy terraform code"
    steps:
      - task: DownloadSecureFile@1
        displayName: 'Download passwords file'
        name: tfpasswords
        inputs:
          secureFile: 'notpasswords.tfvars'
        continueOnError: false

      - task: TerraformInstaller@1
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: 'latest'
        continueOnError: false

      - task: TerraformTaskV4@4
        displayName: 'Run Init'
        inputs:
          command: 'init'
          provider: 'azurerm'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: '$(ServiceConnectionName)'
          backendAzureRmResourceGroupName: '$(beStrgRG)'
          backendAzureRmStorageAccountName: '$(beStrg)'
          backendAzureRmContainerName: '$(beStrgCon)'
          backendAzureRmKey: 'beStrgKey'
        continueOnError: false

      - task: TerraformTaskV4@4
        displayName: 'Select Workspace'
        inputs:
          provider: 'azurerm'
          command: 'custom'
          customCommand: 'workspace'
          commandOptions: 'select -or-create $(env)'
          outputTo: 'console'
          environmentServiceNameAzureRM: '$(ServiceConnectionName)'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

      - task: TerraformTaskV4@4
        displayName: 'Run apply'
        inputs:
          command: 'apply'
          commandOptions: '-var-file=$(tfpasswords.secureFilePath)'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceNameAzureRM: $(ServiceConnectionName)
        continueOnError: false
