jobs:
  - job: deply_terraform
    displayName: "Deploy terraform code"
    steps:
      - task: TerraformTaskV4@4
        displayName: 'Select Workspace'
        inputs:
          provider: 'azurerm'
          command: 'custom'
          customCommand: 'workspace'
          commandOptions: 'select $(env)'
          outputTo: 'console'
          environmentServiceNameAzureRM: '$(ServiceConnectionName)'

      - task: TerraformTaskV4@4
        displayName: 'Run apply'
        inputs:
          command: 'apply'
          commandOptions: '-var-file=$(tfpasswords.secureFilePath)'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceNameAzureRM: $(ServiceConnectionName)
        continueOnError: false
