jobs:
  - job: approval
    pool: server
    steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'eoin.healy@canadalifegroup.com'
          allowApproversToApproveTheirOwnRuns: true

  - job: destroy_terraform
    displayName: "destroy terraform resources"
    steps:
      - task: DownloadSecureFile@1
        displayName: 'Download passwords file'
        name: tfpasswords
        inputs:
          secureFile: 'notpasswords.tfvars'
        continueOnError: false

      - task: TerraformInstaller@1
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: 'latest'
        continueOnError: false

      - task: TerraformTaskV4@4
        displayName: 'Run Init'
        inputs:
          command: 'init'
          provider: 'azurerm'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: '$(ServiceConnectionName)'
          backendAzureRmResourceGroupName: '$(beStrgRG)'
          backendAzureRmStorageAccountName: '$(beStrg)'
          backendAzureRmContainerName: '$(beStrgCon)'
          backendAzureRmKey: '$(beStrgKey)'
        continueOnError: false

      - task: TerraformTaskV4@4
        displayName: 'Select Workspace'
        inputs:
          provider: 'azurerm'
          command: 'custom'
          customCommand: 'workspace'
          commandOptions: 'select -or-create $(env)'
          outputTo: 'console'
          environmentServiceNameAzureRM: '$(ServiceConnectionName)'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

      - task: TerraformTaskV4@4
        displayName: 'Run destroy'
        inputs:
          command: 'destroy'
          commandOptions: '-var-file=$(tfpasswords.secureFilePath)'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceNameAzureRM: $(ServiceConnectionName)
        continueOnError: false
