jobs:
  - job: plan_terraform
    displayName: "Run Plan"
    
    steps:
      - task: TerraformTaskV4@4
        inputs:
          command: 'plan'
          commandOptions: '-var-file notpasswords.tfvars'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceNameAzureRM: $(ServiceConnectionName)
        continueOnError: false

