jobs:
  - job: prep_terraform
    displayName: "Setup terraform"
    
    steps:
      - task: TerraformInstaller@1
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: 'latest'
      
      - task: TerraformTaskV4@4
        displayName: 'Run Init'
        inputs:
          command: 'init'
          provider: 'azurerm'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: '$(ServiceConnectionName)'
          backendAzureRmResourceGroupName: '$(beStrgRG)'
          backendAzureRmStorageAccountName: '$(beStrg)'
          backendAzureRmContainerName: '$(beStrgCon)'
          backendAzureRmKey: 'beStrgKey'

      - task: TerraformTaskV4@4
        displayName: 'Run validate'
        inputs:
          command: 'validate'
          provider: 'azurerm'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

