jobs:
  - job: prep_terraform
    displayName: "Setup terraform"
    
    steps:
      - task: TerraformInstaller@1
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: 'latest'
      
      - task: TerraformCLI@2
        displayName: 'Run Init'
        inputs:
          command: 'init'
          backendType: 'azurerm'
          allowTelemetryCollection: false
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: $(ServiceConnectionName)

      - task: TerraformCLI@2
        displayName: 'Run validate'
        inputs:
          command: 'validate'
          allowTelemetryCollection: false
          workingDirectory: '$(System.DefaultWorkingDirectory)'

